---
- name: Create directories
  file:
    path: "{{item}}"
    state: directory
    mode: "0755"
  with_items:
    - "{{deploy_directory}}"
    - "{{deploy_directory}}/config"

- name: Copy telegraf config
  copy:
    src: telegraf.conf
    dest: "{{deploy_directory}}/config"

- name: Copy prometheus config
  copy:
    src: prometheus.yml
    dest: "{{deploy_directory}}/config"

- name: Copy grafana config
  copy:
    src: grafana
    dest: "{{deploy_directory}}/config/"

- name: Send docker-compose to deploy
  template:
    src: docker-compose.yml.j2
    dest: "{{deploy_directory}}/docker-compose.yml"

- name: Start containers
  docker_compose:
    project_src: "{{deploy_directory}}"
    project_name: "monitoring"
    restarted: yes
    build: no
    pull: yes
