"""empty message

Revision ID: 285781e3c1d9
Revises: 1a67d2f02e18
Create Date: 2020-04-27 21:50:30.682167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '285781e3c1d9'
down_revision = '1a67d2f02e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('params', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('params', 'params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('params', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('params', 'config')
    # ### end Alembic commands ###
