"""empty message

Revision ID: 7f9eac1d2054
Revises: 285781e3c1d9
Create Date: 2020-04-27 21:51:38.934115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f9eac1d2054'
down_revision = '285781e3c1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('place_id', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('place_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='params_pkey')
    )
    op.drop_table('configs')
    # ### end Alembic commands ###
