FROM ubuntu:16.04

WORKDIR /app
RUN apt update && apt install -y python3 python3-pip wget qt4-default

RUN wget https://github.com/DFRobot/uPyCraft/raw/master/uPyCraft_linux_V1.0
RUN chmod +x uPyCraft_linux_V1.0

CMD ./uPyCraft_linux_V1.0
